# Imports

In [5]:
#Packages

#Standard library
from pathlib import Path
import sys
import warnings

#Data/Plots
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


#Warnings + Misc
%matplotlib inline
warnings.filterwarnings("ignore", category=FutureWarning)
pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 160)
sns.set_theme(style="whitegrid", context="talk")

In [8]:
#Data
df = pd.read_csv('../data/joined_data.csv')
df.head()

,date,headline_count,mean_sentiment,median_sentiment,sentiment_std,sentiment_min,sentiment_max,sentiment_neg_pct,sentiment_pos_pct,unique_sources_count,unique_sources,day_of_week,cpi_Above -0.1%,cpi_Above 0.0%,cpi_Above 0.1%,cpi_Above 0.2%,cpi_Above 0.3%,cpi_Above 0.4%,cpi_Above 0.5%,cpi_expected_cpi,cpi_implied_volatility,cpi_above_0_1_rolling_std,cpi_above_0_0_rolling_std,cpi_above_0_2_rolling_std,cpi_above_0_3_rolling_std,cpi_above_0_4_rolling_std,cpi_above_0_5_rolling_std,cpi_above_0_1_rolling_change,cpi_above_0_0_rolling_change,cpi_above_0_2_rolling_change,cpi_above_0_3_rolling_change,cpi_above_0_4_rolling_change,cpi_above_0_5_rolling_change,cpi_slope_above_0_1_to_above_0_0,cpi_slope_above_0_0_to_above_0_1,cpi_slope_above_0_1_to_above_0_2,cpi_slope_above_0_2_to_above_0_3,cpi_slope_above_0_3_to_above_0_4,cpi_slope_above_0_4_to_above_0_5,cpi_right_tail_sum,cpi_right_tail_share,cpi_left_tail_gap,cpi_threshold_spread,cpi_Above 0.6%,cpi_above_0_6_rolling_std,cpi_above_0_6_rolling_change,cpi_slope_above_0_5_to_above_0_6,cpi_core_Above 0.0%,cpi_core_Above 0.1%,cpi_core_Above 0.2%,cpi_core_Above 0.3%,cpi_core_Above 0.4%,cpi_core_Above 0.5%,cpi_core_Above 0.6%,cpi_core_expected_cpi,cpi_core_implied_volatility,cpi_core_above_0_0_rolling_std,cpi_core_above_0_1_rolling_std,cpi_core_above_0_2_rolling_std,cpi_core_above_0_3_rolling_std,...,cpi_yoy_above_2_3_rolling_std,cpi_yoy_above_2_4_rolling_std,cpi_yoy_above_2_5_rolling_std,cpi_yoy_above_2_6_rolling_std,cpi_yoy_above_2_7_rolling_std,cpi_yoy_above_2_8_rolling_std,cpi_yoy_above_2_9_rolling_std,cpi_yoy_above_3_0_rolling_std,cpi_yoy_above_3_1_rolling_std,cpi_yoy_above_2_2_rolling_change,cpi_yoy_above_2_3_rolling_change,cpi_yoy_above_2_4_rolling_change,cpi_yoy_above_2_5_rolling_change,cpi_yoy_above_2_6_rolling_change,cpi_yoy_above_2_7_rolling_change,cpi_yoy_above_2_8_rolling_change,cpi_yoy_above_2_9_rolling_change,cpi_yoy_above_3_0_rolling_change,cpi_yoy_above_3_1_rolling_change,cpi_yoy_slope_above_2_2_to_above_2_3,cpi_yoy_slope_above_2_3_to_above_2_4,cpi_yoy_slope_above_2_4_to_above_2_5,cpi_yoy_slope_above_2_5_to_above_2_6,cpi_yoy_slope_above_2_6_to_above_2_7,cpi_yoy_slope_above_2_7_to_above_2_8,cpi_yoy_slope_above_2_8_to_above_2_9,cpi_yoy_slope_above_2_9_to_above_3_0,cpi_yoy_slope_above_3_0_to_above_3_1,cpi_yoy_right_tail_sum,cpi_yoy_right_tail_share,cpi_yoy_left_tail_gap,cpi_yoy_threshold_spread,cpi_yoy_Above 1.8%,cpi_yoy_Above 1.9%,cpi_yoy_Above 2.0%,cpi_yoy_Above 2.1%,cpi_yoy_above_1_8_rolling_std,cpi_yoy_above_1_9_rolling_std,cpi_yoy_above_2_0_rolling_std,cpi_yoy_above_2_1_rolling_std,cpi_yoy_above_1_8_rolling_change,cpi_yoy_above_1_9_rolling_change,cpi_yoy_above_2_0_rolling_change,cpi_yoy_above_2_1_rolling_change,cpi_yoy_slope_above_1_8_to_above_1_9,cpi_yoy_slope_above_1_9_to_above_2_0,cpi_yoy_slope_above_2_0_to_above_2_1,cpi_yoy_slope_above_2_1_to_above_2_2,cpi_yoy_Above 3.2%,cpi_yoy_Above 3.3%,cpi_yoy_Above 3.4%,cpi_yoy_above_3_2_rolling_std,cpi_yoy_above_3_3_rolling_std,cpi_yoy_above_3_4_rolling_std,cpi_yoy_above_3_2_rolling_change,cpi_yoy_above_3_3_rolling_change,cpi_yoy_above_3_4_rolling_change,cpi_yoy_slope_above_3_1_to_above_3_2,cpi_yoy_slope_above_3_2_to_above_3_3,cpi_yoy_slope_above_3_3_to_above_3_4
0,2025-01-01,2,0.500000,0.50,0.000000,0.50,0.50,0,0,2,"['WJW FOX 8 News Cleveland', '/FILM']",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-03,2,0.250000,0.25,0.000000,0.25,0.25,2,0,2,"['Raw Story', 'The Mercury News']",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.000000,0.0,0.000000,6.682159,0.000000,0.0,0.000000,0.000000,0.00,0.0,0.0,0.0,0.00,-9.45,0.00,0.0,0.0,0.00,NaN,NaN,NaN,NaN,-2.55,16.74,NaN,NaN,15.00,593.63,8.64216,0.0,72.55,68.69,NaN,77.36,NaN,0.000000,0.0,0.000000,0.0,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-01-05,1,0.500000,0.50,0.000000,0.50,0.50,0,0,1,['Washington Examiner'],6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-01-06,3,0.500000,0.50,0.000000,0.50,0.50,0,0,3,"['Newser', 'The Dallas Morning News', 'New Yor...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,4.618802,0.0,0.023094,0.317543,12.592009,0.0,6.928203,0.190526,9.78,0.0,8.0,0.0,-0.04,-10.00,-21.81,0.0,-12.0,-0.33,NaN,NaN,NaN,NaN,-2.04,38.00,NaN,NaN,3.33,618.63,6.58117,0.0,81.33,94.00,NaN,94.00,NaN,14.612735,0.0,9.084962,0.0,25.31,0.0,16.64,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-01-07,6,0.458333,0.50,0.102062,0.25,0.50,1,0,4,"['New York Post', 'The Dallas Morning News', '...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Cleaning

In [9]:
# Clean dataset
if 'df' not in globals() or not isinstance(df, pd.DataFrame):
    df = pd.read_csv('data/joined_data.csv')

clean_df = df.copy()
clean_df['date'] = pd.to_datetime(clean_df['date'], errors='coerce')
clean_df = (
    clean_df.dropna(subset=['date'])
    .sort_values('date')
    .drop_duplicates(subset=['date'])
    .reset_index(drop=True)
)

drop_all_missing = [c for c in clean_df.columns if clean_df[c].isna().all()]
drop_high_missing = [c for c in clean_df.columns if clean_df[c].isna().mean() > 0.90]
clean_df = clean_df.drop(columns=sorted(set(drop_all_missing + drop_high_missing)))

if {'sentiment_neg_pct', 'sentiment_pos_pct', 'headline_count'}.issubset(clean_df.columns):
    denom = clean_df['headline_count'].replace(0, np.nan)
    clean_df['sentiment_neg_rate'] = (clean_df['sentiment_neg_pct'] / denom).clip(0, 1).fillna(0)
    clean_df['sentiment_pos_rate'] = (clean_df['sentiment_pos_pct'] / denom).clip(0, 1).fillna(0)

if 'unique_sources' in clean_df.columns:
    clean_df = clean_df.drop(columns=['unique_sources'])

market_cols = [c for c in clean_df.columns if c.startswith('cpi')]
if market_cols:
    clean_df[market_cols] = clean_df[market_cols].ffill().bfill()

print(f'clean_df shape: {clean_df.shape}')
clean_df.head()

clean_df shape: (249, 139)

,date,headline_count,mean_sentiment,median_sentiment,sentiment_std,sentiment_min,sentiment_max,sentiment_neg_pct,sentiment_pos_pct,unique_sources_count,day_of_week,cpi_Above -0.1%,cpi_Above 0.0%,cpi_Above 0.1%,cpi_Above 0.2%,cpi_Above 0.3%,cpi_Above 0.4%,cpi_Above 0.5%,cpi_expected_cpi,cpi_implied_volatility,cpi_above_0_1_rolling_std,cpi_above_0_0_rolling_std,cpi_above_0_2_rolling_std,cpi_above_0_3_rolling_std,cpi_above_0_4_rolling_std,cpi_above_0_5_rolling_std,cpi_above_0_1_rolling_change,cpi_above_0_0_rolling_change,cpi_above_0_2_rolling_change,cpi_above_0_3_rolling_change,cpi_above_0_4_rolling_change,cpi_above_0_5_rolling_change,cpi_slope_above_0_1_to_above_0_0,cpi_slope_above_0_0_to_above_0_1,cpi_slope_above_0_1_to_above_0_2,cpi_slope_above_0_2_to_above_0_3,cpi_slope_above_0_3_to_above_0_4,cpi_slope_above_0_4_to_above_0_5,cpi_right_tail_sum,cpi_right_tail_share,cpi_left_tail_gap,cpi_threshold_spread,cpi_core_Above 0.0%,cpi_core_Above 0.1%,cpi_core_Above 0.2%,cpi_core_Above 0.3%,cpi_core_Above 0.4%,cpi_core_Above 0.5%,cpi_core_expected_cpi,cpi_core_implied_volatility,cpi_core_above_0_0_rolling_std,cpi_core_above_0_1_rolling_std,cpi_core_above_0_2_rolling_std,cpi_core_above_0_3_rolling_std,cpi_core_above_0_4_rolling_std,cpi_core_above_0_5_rolling_std,cpi_core_above_0_6_rolling_std,cpi_core_above_0_0_rolling_change,cpi_core_above_0_1_rolling_change,cpi_core_above_0_2_rolling_change,...,cpi_yoy_Above 2.8%,cpi_yoy_Above 2.9%,cpi_yoy_Above 3.0%,cpi_yoy_Above 3.1%,cpi_yoy_expected_cpi,cpi_yoy_implied_volatility,cpi_yoy_above_2_2_rolling_std,cpi_yoy_above_2_3_rolling_std,cpi_yoy_above_2_4_rolling_std,cpi_yoy_above_2_5_rolling_std,cpi_yoy_above_2_6_rolling_std,cpi_yoy_above_2_7_rolling_std,cpi_yoy_above_2_8_rolling_std,cpi_yoy_above_2_9_rolling_std,cpi_yoy_above_3_0_rolling_std,cpi_yoy_above_3_1_rolling_std,cpi_yoy_above_2_2_rolling_change,cpi_yoy_above_2_3_rolling_change,cpi_yoy_above_2_4_rolling_change,cpi_yoy_above_2_5_rolling_change,cpi_yoy_above_2_6_rolling_change,cpi_yoy_above_2_7_rolling_change,cpi_yoy_above_2_8_rolling_change,cpi_yoy_above_2_9_rolling_change,cpi_yoy_above_3_0_rolling_change,cpi_yoy_above_3_1_rolling_change,cpi_yoy_slope_above_2_2_to_above_2_3,cpi_yoy_slope_above_2_3_to_above_2_4,cpi_yoy_slope_above_2_4_to_above_2_5,cpi_yoy_slope_above_2_5_to_above_2_6,cpi_yoy_slope_above_2_6_to_above_2_7,cpi_yoy_slope_above_2_7_to_above_2_8,cpi_yoy_slope_above_2_8_to_above_2_9,cpi_yoy_slope_above_2_9_to_above_3_0,cpi_yoy_slope_above_3_0_to_above_3_1,cpi_yoy_right_tail_sum,cpi_yoy_right_tail_share,cpi_yoy_left_tail_gap,cpi_yoy_threshold_spread,cpi_yoy_Above 1.8%,cpi_yoy_Above 2.0%,cpi_yoy_above_1_8_rolling_std,cpi_yoy_above_1_9_rolling_std,cpi_yoy_above_2_0_rolling_std,cpi_yoy_above_2_1_rolling_std,cpi_yoy_above_1_8_rolling_change,cpi_yoy_above_1_9_rolling_change,cpi_yoy_above_2_0_rolling_change,cpi_yoy_above_2_1_rolling_change,cpi_yoy_Above 3.2%,cpi_yoy_Above 3.4%,cpi_yoy_above_3_2_rolling_std,cpi_yoy_above_3_3_rolling_std,cpi_yoy_above_3_4_rolling_std,cpi_yoy_above_3_2_rolling_change,cpi_yoy_above_3_3_rolling_change,cpi_yoy_above_3_4_rolling_change,cpi_yoy_slope_above_3_1_to_above_3_2,sentiment_neg_rate,sentiment_pos_rate
0,2025-01-01,2,0.500000,0.50,0.000000,0.50,0.50,0,0,2,2,95.0,91.3,84.0,68.0,54.82,11.0,1.0,0.20682,0.184709,0.0,0.0,10.606602,0.0,0.0,0.0,0.0,0.0,-15.0,0.0,0.0,0.0,-2.0,16.0,16.0,13.18,17.0,10.0,0.0,0.0,0.0,29.18,95.0,89.0,65.0,29.81,7.0,3.0,0.18381,0.167033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,68.81,17.61,28.0,13.00,0.59363,1.584425,0.000000,0.0,0.000000,0.0,0.000000,6.682159,0.000000,0.0,0.000000,0.000000,0.00,0.0,0.0,0.0,0.00,-9.45,0.00,0.0,0.0,0.00,2.0,2.76,-8.5,16.0,-2.55,16.74,27.65,10.77,15.00,593.63,8.64216,0.0,72.55,68.69,77.36,0.000000,0.0,0.000000,0.0,0.00,0.0,0.00,0.0,10.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,2025-01-03,2,0.250000,0.25,0.000000,0.25,0.25,2,0,2,4,95.0,91.3,84.0,68.0,54.82,11.0,1.0,0.20682,0.184709,0.0,0.0,10.606602,0.0,0.0,0.0,0.0,0.0,-15.0,0.0,0.0,0.0,-2.0,16.0,16.0,13.18,17.0,10.0,0.0,0.0,0.0,29.18,95.0,89.0,65.0,29.81,7.0,3.0,0.18381,0.167033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,68.81,17.61,28.0,13.00,0.59363,1.584425,0.000000,0.0,0.000000,0.0,0.000000,6.682159,0.000000,0.0,0.000000,0.000000,0.00,0.0,0.0,0.0,0.00,-9.45,0.00,0.0,0.0,0.00,2.0,2.76,-8.5,16.0,-2.55,16.74,27.65,10.77,15.00,593.63,8.64216,0.0,72.55,68.69,77.36,0.000000,0.0,0.000000,0.0,0.00,0.0,0.00,0.0,10.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0
2,2025-01-05,1,0.500000,0.50,0.000000,0.50,0.50,0,0,1,6,95.0,91.3,84.0,68.0,54.82,11.0,1.0,0.20682,0.184709,0.0,0.0,10.606602,0.0,0.0,0.0,0.0,0.0,-15.0,0.0,0.0,0.0,-2.0,16.0,16.0,13.18,17.0,10.0,0.0,0.0,0.0,29.18,95.0,89.0,65.0,29.81,7.0,3.0,0.18381,0.167033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,68.81,17.61,28.0,13.00,0.59363,1.584425,0.000000,0.0,0.000000,0.0,0.000000,6.682159,0.000000,0.0,0.000000,0.000000,0.00,0.0,0.0,0.0,0.00,-9.45,0.00,0.0,0.0,0.00,2.0,2.76,-8.5,16.0,-2.55,16.74,27.65,10.77,15.00,593.63,8.64216,0.0,72.55,68.69,77.36,0.000000,0.0,0.000000,0.0,0.00,0.0,0.00,0.0,10.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,2025-01-06,3,0.500000,0.50,0.000000,0.50,0.50,0,0,3,0,95.0,91.3,84.0,68.0,54.82,11.0,1.0,0.20682,0.184709,0.0,0.0,10.606602,0.0,0.0,0.0,0.0,0.0,-15.0,0.0,0.0,0.0,-2.0,16.0,16.0,13.18,17.0,10.0,0.0,0.0,0.0,29.18,95.0,89.0,65.0,29.81,7.0,3.0,0.18381,0.167033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,47.00,17.61,16.0,12.67,0.61863,1.587401,5.646486,0.0,4.618802,0.0,0.023094,0.317543,12.592009,0.0,6.928203,0.190526,9.78,0.0,8.0,0.0,-0.04,-10.00,-21.81,0.0,-12.0,-0.33,2.0,2.76,-8.5,16.0,-2.04,38.00,27.65,10.77,3.33,618.63,6.58117,0.0,81.33,94.00,94.00,14.612735,0.0,9.084962,0.0,25.31,0.0,16.64,0.0,10.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,2025-01-07,6,0.458333,0.50,0.102062,0.25,0.50,1,0,4,1,95.0,91.3,84.0,68.0,54.82,11.0,1.0,0.20682,0.184709,0.0,0.0,10.606602,0.0,0.0,0.0,0.0,0.0,-15.0,0.0,0.0,0.0,-2.0,16.0,16.0,13.18,17.0,10.0,0.0,0.0,0.0,29.18,95.0,89.0,65.0,29.81,7.0,3.0,0.18381,0.167033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,47.00,17.61,16.0,12.67,0.61863,1.587401,5.646486,0.0,4.618802,0.0,0.023094,0.317543,12.592009,0.0,6.928203,0.190526,9.78,0.0,8.0,0.0,-0.04,-10.00,-21.81,0.0,-12.0,-0.33,2.0,2.76,-8.5,16.0,-2.04,38.00,27.65,10.77,3.33,618.63,6.58117,0.0,81.33,94.00,94.00,14.612735,0.0,9.084962,0.0,25.31,0.0,16.64,0.0,10.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.0

In [ ]:
# Market-specific sub-dataframes
if 'clean_df' not in globals() or not isinstance(clean_df, pd.DataFrame):
    raise ValueError('Run the Clean dataset cell first to create clean_df.')

base_cols = [
    c for c in clean_df.columns
    if not c.startswith('cpi_') and not c.startswith('cpi_core_') and not c.startswith('cpi_yoy_')
]

cpi_cols = [c for c in clean_df.columns if c.startswith('cpi_') and not c.startswith('cpi_core_') and not c.startswith('cpi_yoy_')]
cpi_core_cols = [c for c in clean_df.columns if c.startswith('cpi_core_')]
cpi_yoy_cols = [c for c in clean_df.columns if c.startswith('cpi_yoy_')]

cpi_df = clean_df[base_cols + cpi_cols].copy()
cpi_core_df = clean_df[base_cols + cpi_core_cols].copy()
cpi_yoy_df = clean_df[base_cols + cpi_yoy_cols].copy()

print('cpi_df:', cpi_df.shape)
print('cpi_core_df:', cpi_core_df.shape)
print('cpi_yoy_df:', cpi_yoy_df.shape)
cpi_df.head()